name: pomodoro
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0-72.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_mobx: ^2.1.0
  mobx: ^2.2.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mobx_codegen: ^2.4.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
